#!/bin/bash
set -e

# Parse version flag
VERSION=""
if [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
  VERSION="$2"
  shift 2
fi

echo "📦 Bundling vanilla JS artifact with source metadata..."

# Check if src directory exists
if [ ! -d "src" ]; then
  echo "❌ Error: No src/ directory found in current directory."
  echo "   Run this script from your project root (the directory containing src/)."
  exit 1
fi

# Check if index.html exists in src
if [ ! -f "src/index.html" ]; then
  echo "❌ Error: No index.html found in src/ directory."
  echo "   The src/ directory must contain an index.html file."
  exit 1
fi

# Initialize package.json if it doesn't exist
if [ ! -f "package.json" ]; then
  echo "📝 Creating minimal package.json..."
  cat > package.json << 'EOF'
{
  "name": "vanilla-artifact",
  "version": "1.0.0",
  "private": true
}
EOF
fi

# Install bundling dependencies (only if node_modules doesn't exist)
if [ ! -d "node_modules" ]; then
  echo "📦 Installing bundling dependencies..."
  npm install --save-dev parcel @parcel/config-default html-inline
else
  echo "✓ Dependencies already installed (skipping npm install)"
fi

# Create minimal Parcel config
if [ ! -f ".parcelrc" ]; then
  echo "🔧 Creating Parcel configuration..."
  cat > .parcelrc << 'EOF'
{
  "extends": "@parcel/config-default"
}
EOF
fi

# Clean previous build
echo "🧹 Cleaning previous build..."
rm -rf dist .parcel-cache

# Collect source files metadata from src/ directory
echo "📋 Collecting source file metadata from src/..."
SOURCE_MANIFEST="{"

# Function to encode file content as base64
encode_file() {
    base64 -w 0 "$1" 2>/dev/null || base64 "$1"
}

# Function to get relative path from src/
get_relative_path() {
    echo "$1" | sed 's|^src/||'
}

# Track files and their content from src/ directory
first=true

# Find all HTML, CSS, JS files in src/
for file in $(find src -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \)); do
    if [ "$first" = true ]; then
        first=false
    else
        SOURCE_MANIFEST="$SOURCE_MANIFEST,"
    fi
    
    # Get relative path from src/
    rel_path=$(get_relative_path "$file")
    
    # Encode the file content
    encoded_content=$(encode_file "$file")
    
    SOURCE_MANIFEST="$SOURCE_MANIFEST\"$rel_path\":\"$encoded_content\""
done

# Find all image files in src/images/
if [ -d "src/images" ]; then
    for file in $(find src/images -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.svg" -o -name "*.webp" \)); do
        if [ "$first" = true ]; then
            first=false
        else
            SOURCE_MANIFEST="$SOURCE_MANIFEST,"
        fi
        
        # Get relative path from src/
        rel_path=$(get_relative_path "$file")
        
        # Encode the file content
        encoded_content=$(encode_file "$file")
        
        SOURCE_MANIFEST="$SOURCE_MANIFEST\"$rel_path\":\"$encoded_content\""
    done
fi

SOURCE_MANIFEST="$SOURCE_MANIFEST}"

# Build with Parcel (from src/index.html)
echo "🔨 Building with Parcel..."
npx parcel build src/index.html --dist-dir dist --no-source-maps

# Inline everything into single HTML
echo "🎯 Inlining all assets into single HTML file..."
npx html-inline dist/index.html > bundle.temp.html

# Determine output filename
if [ -n "$VERSION" ]; then
  OUTPUT_FILE="bundle-${VERSION}.html"
else
  OUTPUT_FILE="bundle.html"
fi

# Add source metadata as a comment at the end
echo "🔖 Embedding source metadata..."
cat bundle.temp.html > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "<!-- Metadata generated by the 'vanilla-artifact-builder' skill for Claude and can be interpreted by the same skill. VANILLA-ARTIFACT-SOURCE-MAP-V1 $SOURCE_MANIFEST -->" >> "$OUTPUT_FILE"

rm bundle.temp.html

# Get file size
FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)

echo ""
echo "✅ Bundle complete!"
echo "📄 Output: $OUTPUT_FILE ($FILE_SIZE)"
echo "🔖 Source metadata embedded for unbundling"
echo ""
if [ -n "$VERSION" ]; then
  echo "Version: $VERSION"
  
  # List all bundle versions
  if ls bundle*.html 1> /dev/null 2>&1; then
    echo ""
    echo "All versions:"
    ls -lh bundle*.html | awk '{print "  " $9 " (" $5 ")"}'
  fi
fi
echo ""
echo "This single HTML file is ready to use as a Claude artifact."
echo "Use unbundle-vanilla-artifact.sh to extract the original source files."

